# Generated by Django 4.0.3 on 2022-04-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='photo_out',
        ),
        migrations.AddField(
            model_name='app',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
