# Generated by Django 4.0.3 on 2022-04-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_app_photo_out_app_height_app_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='photo_mod',
            field=models.ImageField(blank=True, null=None, upload_to='photos_mod'),
        ),
        migrations.AlterField(
            model_name='app',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
