# Generated by Django 4.0.3 on 2022-04-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_app_photo_mod_alter_app_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
